### ISSUE TITLE
Using `template` input returns and outputs the value

### ISSUE THREAD

**Issue by LeoColomb** [controlplaneio/kubesec-action#2]
This is an example of steps part of my SAST workflow for GitHub Actions.

```yaml
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Helm
        uses: azure/setup-helm@v1.1
      - name: Render chart
        run: helm template kubesec charts/app > app-template.yml
      - name: Run kubesec scanner
        uses: controlplaneio/kubesec-action@v0.0.2
        with:
          input: app-template.yml
          format: template
          template: '@/templates/sarif.tpl'
          output: kubesec-results.sarif
          exit-code: "0"
      - run: cat kubesec-results.sarif
```

Whatever is the value of `template` input (here `'@/templates/sarif.tpl'`), the step output and the output file if present both receive the value.

![image](https://user-images.githubusercontent.com/846943/138622576-d460cca8-5e26-4c3f-aff7-99ed8d557629.png)

Of course, different values have been tried, like:
* `'templates/sarif.tpl'`
* `'template/sarif.tpl'`
